# Dockerfile para o Frontend
FROM nginx:alpine

# Copiar o conteúdo do diretório frontend (local) para o diretório de arquivos estáticos do Nginx
COPY . /usr/share/nginx/html

# Expor a porta 80
EXPOSE 80
